require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

